apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: jcdqmwg8a-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/jcdqmwg8a-java-springboot-gitops